project_id = "njowwmgtxkketyiaflfp"

[functions.validate-access-key]
verify_jwt = false

[functions.dashboard-data]
verify_jwt = false

[functions.panel-auth]
verify_jwt = false

[functions.panel-crud]
verify_jwt = false
