// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njowwmgtxkketyiaflfp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qb3d3bWd0eGtrZXR5aWFmbGZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM3NDY1MjEsImV4cCI6MjA4OTMyMjUyMX0.i3c8QaGI8LohSyrer-iT5gb6A0sLI1S6a76pXpqjNAI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});